version: '3.8'

services:
  redis:
    container_name: iqrediscontainer
    image: redis:latest
    ports:
      - "6358:6379"
    command: redis-server --port 6379
    networks:
      - my-network

  postgres:
    container_name: iqservice-db
    image: postgres:15
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: itservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: omonov2006
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  iqgame-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iqgame-app
    ports:
      - "8086:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://iqservice-db:5432/itservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: omonov2006
      SPRING_REDIS_HOST: iqrediscontainer
      SPRING_REDIS_PORT: 6379
    networks:
      - my-network
    volumes:
      - ./DOCUMENTS:/app/DOCUMENTS:rw

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
